Q1="SELECT COUNT(id) FROM Movie WHERE year<2000;"
Q2="SELECT AVG(rank) FROM Movie WHERE year=1991;"
Q3="SELECT MIN(rank) FROM Movie WHERE year=1991;"
Q4="SELECT fname,lname FROM Actor INNER JOIN Cast ON pid=id WHERE mid=27;"
Q5="SELECT COUNT(mid) FROM Actor INNER JOIN Cast ON id=pid WHERE fname='Jon' AND lname='Dough';"
Q6="SELECT name FROM Movie WHERE name LIKE 'Young Latin Girls%' AND year BETWEEN 2003 AND 2006;"
Q7="SELECT fname,lname FROM Director INNER JOIN MovieDIRECTOR ON `Director`.`id`=did INNER JOIN Movie ON `Movie`.`id`=mid WHERE name LIKE 'Star Trek%';"
Q9="SELECT fname,lname FROM Director INNER JOIN MovieDIRECTOR ON `Director`.`id`=did INNER JOIN Movie ON `Movie`.`id`=mid WHERE year = 2001 GROUP BY did HAVING COUNT(mid)>=4 ORDER BY fname ASC,lname DESC;"
Q10="SELECT GENDER,COUNT(id) FROM Actor GROUP BY GENDER ORDER BY GENDER ASC;"
